package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0051bc)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF1469e8)
val md_theme_light_onPrimaryContainer = Color(0xFFf3f4ff)
val md_theme_light_secondary = Color(0xFF2b5bb5)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF759efd)
val md_theme_light_onSecondaryContainer = Color(0xFF00337c)
val md_theme_light_tertiary = Color(0xFF006076)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF007a95)
val md_theme_light_onTertiaryContainer = Color(0xFFe6f7ff)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFf7f9fb)
val md_theme_light_onBackground = Color(0xFF191c1e)
val md_theme_light_surface = Color(0xFFf7f9fb)
val md_theme_light_onSurface = Color(0xFF191c1e)
val md_theme_light_surfaceVariant = Color(0xFFe0e3e5)
val md_theme_light_onSurfaceVariant = Color(0xFF424654)
val md_theme_light_outline = Color(0xFF727786)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f3)
val md_theme_light_inverseSurface = Color(0xFF2d3133)
val md_theme_light_inversePrimary = Color(0xFFb0c6ff)
